version: "2.0"

services:
  calculixir:
      image: simright/calculixir
      volumes:
          # "host volumes:container volumes"
          - "./workroot:/workroot/"
      entrypoint:
          - bash
          - /app/docker-entrypoint.sh 
      ports:
          # "host ports:container ports"
          - "3000:3000"
